### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by srishti-gupta-me** [srishti-gupta-me/LITG-ML#5]
Not able to work with image cv2.split(img) function, throws error **Not able to unpack, expected 3 found 0**. 

When I am trying to print the data type by print(img.dtype) it throws an error **'NoneType' object has no attribute 'dtype'**

Please refer to **OpenCV.ipynb**

**Comment by akshatha-k** [comment]
'NoneType' errors occur when your image has not loaded / read. 
The other error too is trying to convey that it expects three channels ( RBG) but found none owing to no image. 

Colab is a remote server. So the server will not have the image that you're trying to read. You will manually have to run the script to add image or the source folder to it .
Fix options:
1) Work in your local workspace ( not Colab) and execute the same code just like you executed other codes and it should work. Because your syntax seems fine
2) Upload your images to Colab using any of the methods described [here](https://stackoverflow.com/questions/49186905/loading-images-in-google-colab) . ``` wget <address> ``` has always worked for me.
